# Generated by Django 2.1.5 on 2019-04-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisoksm',
            name='access_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spisoksm',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
