# Generated by Django 2.1.7 on 2019-04-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_spisoksm_departament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spisoksm',
            name='departament',
        ),
    ]
